[package]
name = "burrow"
version = "0.1.0"
edition = "2021"

[dependencies]
fehler = "1.0"
tokio = { version = "1.21", features = ["rt", "macros"] }
tun = { version = "0.1", path = "../tun" }
tun-async = { version = "0.1", path = "../tun-async" }
