[package]
name = "tun-async"
version = "0.1.0"
edition = "2021"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
fehler = "1.0"
tun = { path = "../tun" }
tokio = { version = "1.0", features = ["net"], optional = true }
